import Head from 'next/head'
import Image from 'next/image'
// import logo from "../../../public/images/bloomstack-logo.svg"

const Layout = ({ children, countries, title = "World Trace" }) => {

    return (
        <div className='w-70p m-auto'>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <main className=''>
                <div className="t-center bb-solid pb-2">
                    <img src="/images/bloomstack-logo.svg" alt="bloomstack-logo" className="w-80p md-w-50p lg-w-30p" />
                </div>
                {children}
            </main>
        </div>
    )
}

export default Layout