import Head from 'next/head'

const Layout = ({ children, countries, title = "World Trace" }) => {

    return (
        <div className='w-70p m-auto'>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=''>
                <section className="t-center bg-contrast p-2">
                    logo
                </section>
                {children}
            </main>

            <footer>
                footer
            </footer>
        </div>
    )
}

export default Layout