import CountUp from 'react-countup';
import Head from "next/head"
export const getServerSideProps = async ({ params }) => {
    const res = await fetch(`https://restcountries.com/v3.1/name/${params.id}`)
    const country = await res.json();
    return {
        props: {
            country,
        }
    }
}

const Country = ({ country }) => {
    return (
        <div className="bg-primary pv-5 ph-2">
            <Head>
                <title>{country[0].name.common} {country[0].flag}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <div className="grid-2x1">
                <div className="pos-1_1 bg-secondary elevate-1 round-1 mh-2 p-2">
                    <div className="w-60p m-auto"><img src={country[0].flags.png} alt={country[0].name.common} className="w-100p round-3"></img></div>
                    <h2 className="t-center f-5 c-semantic-primary">{country[0].name.common}</h2>
                    <h3 className="t-center f-3 c-neutral-2">{country[0].region}</h3>
                    <div className="grid-2x1">
                        <section className="pos-1_1 t-center">
                            <h4 className="f-4 c-semantic-primary">
                                <CountUp start={0} end={country[0].population} duration={3} useEasing={true} />
                            </h4>
                            <h5 className="f-3 c-neutral-2">Population</h5>
                        </section>
                        <section className="pos-2_1 t-center">
                            <h4 className="f-4 c-semantic-primary">
                                <CountUp start={0} end={country[0].area} duration={3} useEasing={true} />
                            </h4>
                            <h5 className="f-3 c-neutral-2">Area (KM)</h5>
                        </section>
                    </div>
                </div>

                <div className="pos-2_1 bg-secondary elevate-1 round-1 mr-1 p-2 ph-4 c-semantic-primary">
                    <h5 className="f-4 c-semantic-primary t-center f-upper">Details</h5>
                    <div className="mt-5 pt-3">
                        <div className="grid-2x1 bb-solid bl-solid br-solid b-main-cultured-white-1 ph-2 pv-2">
                            <div className="pos-1_1 label f-2 fw-500 c-neutral-2">Capital</div>
                            <div className="pos-2_1 value f-2 fw-600 t-right pr-2">{country[0].capital.map(c => c).join(", ")}</div>
                        </div>
                        <div className="grid-2x1 bb-solid bl-solid br-solid b-main-cultured-white-1 ph-2 pv-2">
                            <div className="pos-1_1 label f-2 fw-500 c-neutral-2">Languages</div>
                            <div className="pos-2_1 value f-2 fw-600 t-right pr-2">
                                {Object.values(country[0].languages).map(c => c).join(", ")}
                            </div>
                        </div>
                        <div className="grid-2x1 bb-solid bl-solid br-solid b-main-cultured-white-1 ph-2 pv-2">
                            <div className="pos-1_1 label f-2 fw-500 c-neutral-2">Currencies</div>
                            <div className="pos-2_1 value f-2 fw-600 t-right pr-2">
                                {Object.values(country[0].currencies).map(({ name }) => name).join(", ")}
                            </div>
                        </div>
                        <div className="grid-2x1 bb-solid bl-solid br-solid b-main-cultured-white-1 ph-2 pv-2">
                            <div className="pos-1_1 label f-2 fw-500 c-neutral-2">Native Name</div>
                            <div className="pos-2_1 value f-2 fw-600 t-right pr-2">
                                {Object.values(country[0].name.nativeName).map(c => c.official).join(", ")}
                            </div>
                        </div>
                        <div className="grid-2x1 bb-solid bl-solid br-solid b-main-cultured-white-1 ph-2 pv-2">
                            <div className="pos-1_1 label f-2 fw-500 c-neutral-2">Gini</div>
                            <div className="pos-2_1 value f-2 fw-600 t-right pr-2">{Object.values(country[0].gini)}%</div>
                        </div>
                        <div className="grid-3x1 bb-solid bl-solid br-solid b-main-cultured-white-1 ph-2 pv-2">
                            <div className="pos-1_1 label f-2 fw-500 c-neutral-2">Google Maps</div>
                            <div className="pos-2_1 col-span-2 value f-2 fw-600 t-right">
                                <a href={`${country[0].maps.googleMaps}`} className="a bb-solid" >{country[0].maps.googleMaps}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    )
}

export default Country;
